### ISSUE TITLE
LlavaForConditionalGeneration Example Contains Bugs

### ISSUE THREAD

**Issue by mnslarcher** [huggingface/hub-docs#1166]
Hi!

**Doc request**
Fix the [LlavaForConditionalGeneration example](https://huggingface.co/docs/transformers/model_doc/llava#transformers.LlavaForConditionalGeneration.forward.example).

**Additional context**
The current example doesn't work. I suggest:
- Replacing "text" with "prompt" as the argument for the processor, since "text" is never defined.
- Replacing "tokenizer" with "processor", as "tokenizer" is also never defined.
- [Optional] Consider using FP16, which will help people try the example without an expensive GPU.

**Comment by pcuenca** [comment]
Thanks for the report @mnslarcher! Those issues (except the use of `float16`) have been fixed in the `main` branch of `transformers`, see the updated docs here: https://huggingface.co/docs/transformers/main/en/model_doc/llava.

You can always check the latest version of the docs if you select `MAIN` here:

<img width="336" alt="Screenshot 2023-12-15 at 21 02 26" src="https://github.com/huggingface/hub-docs/assets/1177582/38d098b0-2452-415d-a7b5-c50eb60f0f4d">

**Comment by mnslarcher** [comment]
Oh sorry! Next time I'll check there too ;). Great that it has already been fixed.

**Comment by pcuenca** [comment]
@mnslarcher No worries! Thanks for reaching out!
