### ISSUE TITLE
Add a section to documentation for task types

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/hub-docs#244]
[This permalink](https://github.com/huggingface/hub-docs/blob/d06c9b875669fe032e8f4675856c140ce78798df/js/src/lib/interfaces/Types.ts#L589) contains the available task keys.
Every time we want to refer to list of available task in the documentation, we refer to that in our own docstrings or anywhere else. I find it unpleasant, is it okay if we could put available task strings inside our own docs somewhere (instead of code) and refer to that instead?

I realized it when I wanted to put it inside [skops](https://github.com/skops-dev/skops) docs. pinging @adrinjalali

**Comment by osanseviero** [comment]
WDYT @julien-c? I think this makes sense.

It has the huge asterisk that we need to either raise some error or really make sure to avoid being out-of-sync. We went from multiple sources of truth to a single one, so I'm a bit worried of again creating the task types in another place.

**Comment by merveenoyan** [comment]
@osanseviero we could have a section in hub-docs and if someone wants to add a task we can let them add it there as well (and also modify the section for ["Adding a task"](https://huggingface.co/docs/hub/models-tasks) in our docs). Maybe we could add the task keys in [here](https://huggingface.co/docs/hub/models-tasks#whats-a-task). Do you want me to deal with this?

**Comment by julien-c** [comment]
I didn't understand this issue very clearly. 

Is the issue that we don't display the "canonical" list of tasks enough on the website? If it's this issue, then yes your proposal of dynamically adding this (full) list to https://huggingface.co/docs/hub/models-tasks#whats-a-task but also to https://huggingface.co/tasks (which should always display all existing tasks, IMO) is good

But yeah as Omar says we should have a single source of truth otherwise things will diverge fast

**Comment by osanseviero** [comment]
Let's close this as it's outdated and there was not an answer to the above. Let's make sure to have most tasks in /tasks :fire:
