### ISSUE TITLE
Link at https://huggingface.co/docs/transformers/performance#cpu is invalid

### ISSUE THREAD

**Issue by Baicheng-MiQ** [huggingface/hub-docs#248]
As title described, the link https://huggingface.co/docs/transformers/perf_infer_cpu.mdx is invalid.

**Comment by NimaBoscarino** [comment]
Good catch! I think this was a mistake in the docs over on the https://github.com/huggingface/transformers repo, but it seems like it's been fixed in the pre-release version of the docs. You can verify it by choosing "Main" instead of "V4.20.1" here:
<img width="492" alt="image" src="https://user-images.githubusercontent.com/6765188/179468739-0e47bf5d-dad5-42b3-aff8-9bfccca125c9.png">

With the next tagged Transformers release this should be fixed. I'll close this issue, but let me know if you think it should be reopened!
