### ISSUE TITLE
please build xformers wheel for 🤗 A10G

### ISSUE THREAD

**Issue by camenduru** [huggingface/hub-docs#538]
I was building xformers for A10G it tooks more then 1h then I hit this `launch timed out, space was not healthy after 30 min`
is it posible to increase this or am I doing something wrong? this code working with colab, kaggle, google cloud or can you please build the xformers wheel for 🤗 A10G

```py
import os
os.system(f"pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113")
os.system(f"pip wheel git+https://github.com/facebookresearch/xformers#egg=xformers")
os.system(f"pip install huggingface-hub")
from huggingface_hub import create_repo, upload_folder
create_repo("camenduru/xformers", private=False, token="token")
upload_folder(folder_path="/home/user/app", repo_id="camenduru/xformers", commit_message=f"xformers", token="token")
```

**Comment by camenduru** [comment]
@osanseviero  thanks ❤

**Comment by camenduru** [comment]
hi @apolinario did you build [this](https://github.com/apolinario/xformers/releases) with console or spaces please teach me how can I build with spaces or please build for torch==1.12.1+cu113 🤗 A10G

**Comment by apolinario** [comment]
Hey @camenduru, it is probably because building an xformers wheel may _actually_ take more than 30 minutes. One thing you can try to avoid the `launch timed out, space was not healthy after 30 min` -> start a Gradio app on the Space before build time. If you just create a Space without an app, it will never build it 

So you could do something like 
```py
import os
import gradio as gr

def build_xformers(token):
      os.system(f"pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113")
      os.system(f"pip wheel git+https://github.com/facebookresearch/xformers#egg=xformers")
      os.system(f"pip install huggingface-hub")
      from huggingface_hub import create_repo, upload_folder
      create_repo("camenduru/xformers", private=False, token=token)
      upload_folder(folder_path="/home/user/app", repo_id="camenduru/xformers", commit_message=f"xformers", token="token")

app = gr.Interface(fn=build_xformers, inputs="text", outputs=[])
app.launch()
```
Then probably you can build without a timeout 
I built this build inside the Space but using an internal SSH terminal to extract the wheels after. 
I could do that with torch==1.12.1 there's one _hack_ you would do to avoid

**Comment by camenduru** [comment]
thanks @apolinario ❤ I will try

**Comment by camenduru** [comment]
if someone needs 🚀 `!pip install https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.15/xformers-0.0.15.dev0+4c06c79.d20221205-cp38-cp38-linux_x86_64.whl`
