### ISSUE TITLE
Duplicated spaces can not get updates 

### ISSUE THREAD

**Issue by camenduru** [huggingface/hub-docs#551]
User will never know there is an update in the main repo, we need something like github sync fork
![Screenshot 2022-12-10 130111](https://user-images.githubusercontent.com/54370274/206849039-e35e52fd-1894-4321-9f66-9d55099c81ec.jpg)

**Comment by osanseviero** [comment]
Hey there, thanks for the feedback!

Spaces duplicates are not designed to be like forks. In that sense, they keep a simple structure by not having a forced linking with the original repo - the reason this is done like this is because duplicates often are more starting points for new projects rather than the same one. You can work locally though

```
git remote set-url upstream <url>
git pull upstream main
```

**Comment by camenduru** [comment]
@osanseviero thanks ❤good idea but I can't put `pull upstream` in main repo I need user permission, I will find an another way maybe I can implement update mechanism inside the app 🤔
