### ISSUE TITLE
Aribtrary streamlit entry-point

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/hub-docs#666]
In Hugging Face Spaces we can use Streamlit. This is awesome! Currently, it is expected that the app has just one entry-point, specifically `app.py`. In more complex projects, that is not feasible however. It would therefore be great if we can optionally specify the following arguments in the space configuration in the README:

- root_dir: root dir to call the `streamlit run` command from (must be sub-directory of main directory)
- app_file: file to run as entry-point

The runner script could then automatically do:

```shell
cd "$root_dir"
streamlit run $app_file
```

**Comment by Wauplin** [comment]
Hi @BramVanroy, do you have an example of such a project? If I understand correctly, the problem with doing directly
```
streamlit run folder/app.py
```
is that the context is not the right one, right? Because I don't see how a Space could have several entrypoints (it would mean several UIs/several ports to watch ?)

A solution to your problem would be to use a [Docker Space](https://huggingface.co/docs/hub/spaces-sdks-docker) where you have a full control over the entrypoint. As I'm not sure how much demand we would have on such a feature request, I don't think we will implement it in the near future (maybe I'm wrong - cc @julien-c @coyotte508).

**Comment by Wauplin** [comment]
(note: I transferred this issue from https://github.com/huggingface/huggingface_hub to https://github.com/huggingface/hub-docs. `huggingface_hub` is the repo related to the Python client only :))

**Comment by julien-c** [comment]
Hi @BramVanroy, you can use `app_file: ...` in your Space config, see https://huggingface.co/docs/hub/spaces-config-reference

> app_file : string
> Path to your main application file (which contains either gradio or streamlit Python code, or static html code).
> Path is relative to the root of the repository.

let us know if this doesn't work!

**Comment by BramVanroy** [comment]
Perfect, thanks!
